### ISSUE TITLE
Add contributors to readme

### ISSUE THREAD

**Issue by alesbe** [alesbe/sorting-visualizer#19]
This issue is just for adding contributors to readme, thanks to everyone!

**Comment by alesbe** [comment]
@all-contributors please add @BlueSkeleton for code

**Comment by alesbe** [comment]
@all-contributors please add @ariajanke for code and bug

**Comment by alesbe** [comment]
@all-contributors please add @bazuin-32  for bug, code, ideas, infra, platform

**Comment by alesbe** [comment]
I'm closing the issue for now, I want to configure some things before adding the contributors table to readme, sorry for the notifications! 🙏

**Comment by ghost** [comment]
don't sweat it :p
