### ISSUE TITLE
[BUG]: Source code doesn't compile.

### ISSUE THREAD

**Issue by luki3122** [alesbe/sorting-visualizer#29]
## Describe you problem:
Source code doesn't compile.

## Steps to reproduce (optional):
install.sh

## Additional info (optional):
sorting-visualizer/src/SortController.h:27:33:
>error: copying member subobject of type 'std::atomic<bool>' invokes deleted constructor
std::atomic<bool> _interrupt = false;

sorting-visualizer/src/SortAlgorithms.cpp:215:11:
>error: out-of-line definition of 'bogoSort' does not match any declaration in namespace 'algo'
int algo::bogoSort(std::vector<Sortable>& sortElements, int timeSleep)

## Possible fix (optional):
std::atomic _interrupt = { false };
Add required argument to bogosort

## OS
- [x] : Windows
- [x] : Mac OS
- [x] : Linux

**Comment by alesbe** [comment]
Thanks for your interest! I don't know how I didn't realize this before, I think that I had some issues with branches and messed up something.

Thanks again for fixing the issue yourself!, Also, using `dev` instead of `main` for the PR would be perfect, but don't worry about it :)
